# Python - Numpy Tutorial

## Introduction

Python is a great general-purpose programming language on its own, but with the help of a few popular libraries (numpy, scipy, matplotlib) it becomes a powerful environment for scientific computing.

### Main topics
* **Basic Python:**
    * Basic data types (Containers, Lists, Dictionaries, Sets, Tuples)
    * Flow Control (if, else)
    * Loops
    * Functions
* **Numpy:** 
    * Arrays, Array indexing, Array math

## Basics of Python

### Python versions

There are currently two different supported versions of **Python, 2.7 and 3.7.** 
* Python 3.* is what will be used
You can check your Python version at the command line by running `python --version`.

In [1]:
from platform import python_version ## Importing the function 'python_version' from module 'platform'

print(python_version()) ## To print something in python 3* simply call the print()

3.6.5


### Basic data types

#### Numbers

Integers and floats work as you would expect from other languages:

In [2]:
x = 3
print(x, type(x))
3, 2
x, type(x) # Notebook cell output

3 <class 'int'>


(3, int)

In [3]:
print(x + 1)   # Addition; 
print(x - 1)   # Subtraction; 
print(x * 2)   # Multiplication;
print(x ** 2)  # Exponentiation;

4
2
6
9


Variables are modified by the "=" sign.

In [4]:
x = 3
x = x + 1
print(x) # Prints "4"
x = 3
x += 1  # The same as x = x + 1
print(x)

4
4


In [5]:
x *= 2    # The same as x = x*2
print(x)  # Prints "8"

8


In python 3, even though we are dividing two integers the result can be a float, just like in Matlab. This is not true for python 2

In [6]:
print(type(x))
print(x/2)

<class 'int'>
4.0


Python also has built-in types for **long integers and complex numbers**; you can find all of the details in the [documentation](https://docs.python.org/3.7/library/stdtypes.html#numeric-types-int-float-long-complex).

#### Booleans

Python implements all of the usual operators for Boolean logic, but uses **English words** rather than symbols (`&&`, `||`, etc.):

In [7]:
t, f = True, False ## Simultaneous assignment of t and f
print(type(t)) # Prints "<type 'bool'>"

<class 'bool'>


Now we let's look at the operations:

In [8]:
print(t and f) # Logical AND;
print(t or f)# Logical OR;
print(not t)   # Logical NOT;
print(t ^ f)  # Logical XOR;
print(t ^ t)  # Logical XOR;

False
True
False
True
False


### Containers

Python includes several built-in container types: lists, dictionaries, sets, and tuples.

#### Lists

A list is the Python equivalent of an array, but is resizeable and can contain elements of different types. **Indexes start at 0 not at 1**

In [9]:
xs = [3, 1, 2]   # Create a list
print(xs)
print(xs[0])
print(xs[-1])     # Neprint(nums)       gative indices count from the end of the list; prints "2"
                  # like gettin x(end) in MATLAB
print(xs[-2])

[3, 1, 2]
3
2
1


In [10]:
xs[2] = 'foo'    # Lists can contain elmements of different types
print(xs)

[3, 1, 'foo']


**Run this multiple times to see what happens**

In [11]:
xs.append('bar') # Add a new element to the end of the list
                 # Modifies the list in place
print(xs)

[3, 1, 'foo', 'bar']


In [12]:
x = xs.pop()     # Remove and return the last element of the list
print(x, xs)

bar [3, 1, 'foo']


One can also concatenate lists by using the *+* operator

In [13]:
a = [1,2]
b = [3, 4, 5]
c = [1, 2 , 3] + ["a", "b", "c"] + [[1,2], [1, 2,3]]
print(c)

[1, 2, 3, 'a', 'b', 'c', [1, 2], [1, 2, 3]]


As usual, you can find all the details about lists in the [documentation](https://docs.python.org/3.7/tutorial/datastructures.html#more-on-lists).

#### Slicing

In addition to accessing list elements one at a time, Python provides concise syntax to access sublists; this is known as slicing

In [14]:
nums = [1, 3, 5, 7, 10]    
print(nums)         # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])    # Get a slice from index 2 to 4 (exclusive)
print(nums[2:])     # Get a slice from index 2 to the end
print(nums[:2])     # Get a slice from the start to index 2 (exclusive)  

[1, 3, 5, 7, 10]
[5, 7]
[5, 7, 10]
[1, 3]


In [15]:
print(nums[:])      # Get a slice of the whole list
print(nums[:-1])    # Slice indices can be negative

[1, 3, 5, 7, 10]
[1, 3, 5, 7]


#### Loops

You can loop over the elements of a list like this:

In [16]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)

cat
dog
monkey


If you want access to the index of each element within the body of a loop, use the built-in `enumerate` function:

In [17]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print(f".{idx}. {animal}")

.0. cat
.1. dog
.2. monkey


#### Tuples

A tuple is an (immutable) ordered list of values. A tuple is in many ways similar to a list; one of the most important differences is that tuples can be used as keys in dictionaries and as elements of sets, while lists cannot. Here is a trivial example:

In [18]:
tup = (1, 2, 3)
print(tup)

(1, 2, 3)


*inmutable*

In [19]:
print(tup[0:2])
tup[0] = 0

(1, 2)


TypeError: 'tuple' object does not support item assignment

### Functions and flow control

Python functions are defined using the `def` keyword. For example:

In [20]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))

negative
zero
positive


### Short Assignmet
Write a function that receives a natural number and **n** and returns a list containing the elemenths of the Fibonacci sequence up to $F_n$ taking into account that:
    $$F_0 = 0$$
    $$F_1 = 1$$ 
    $$F_n = F_{n-2} + F_{n-1}\quad \forall n >=2$$

## Numpy

[Numpy](http://www.numpy.org/) is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. If you are already familiar with MATLAB, you might find this [tutorial](https://docs.scipy.org/doc/numpy-1.15.0/user/numpy-for-matlab-users.html) useful to get started with Numpy.

To use Numpy, we first need to import the `numpy` package:

In [21]:
import numpy as np

### Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [22]:
a = np.array([1, 2, 3])  # Create a rank 1 array
print(a)
a[0] = 5                 # Change an element of the array
print(a)

[1 2 3]
[5 2 3]


In [23]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print(b)

[[1 2 3]
 [4 5 6]]


In [24]:
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


Numpy also provides many functions to create arrays:

In [25]:
a = np.zeros((2,2))  # Create an array of all zeros. The input must be a tuple or a list
print(a)

[[0. 0.]
 [0. 0.]]


In [26]:
b = np.ones(2)
print(b)
b = np.ones((1,2))   # Create an array of all ones
print(b)
b = np.ones((2,1))   # Create an array of all ones
print(b)

[1. 1.]
[[1. 1.]]
[[1.]
 [1.]]


In [27]:
d = np.eye(2)        # Create a 2x2 identity matrix
print(d)

[[1. 0.]
 [0. 1.]]


In [28]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

[[0.25794281 0.9891837 ]
 [0.07263466 0.41233135]]


### Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [29]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(f"x = {x}\n")
print(f"y = {y}\n")
print(f"x + y = {x + y}\n")
print(f"x + y = {np.add(x, y)}\n")
print(np.add(x,y))

x = [[1. 2.]
 [3. 4.]]

y = [[5. 6.]
 [7. 8.]]

x + y = [[ 6.  8.]
 [10. 12.]]

x + y = [[ 6.  8.]
 [10. 12.]]

[[ 6.  8.]
 [10. 12.]]


In [30]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [31]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [32]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [33]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


Note that unlike MATLAB, `*` is elementwise multiplication, not matrix multiplication. We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:

In [34]:
A = np.array([[1,2],[3,4]])
x = np.array([9,10])

# Matrix vector product of vectors; both produce 219
print(A.dot(x))
print(np.dot(A, x))

[29 67]
[29 67]


In [35]:
print(x.dot(x)) # Inner product
print(A.dot(A)) # Matrix by matrix multipication

181
[[ 7 10]
 [15 22]]


Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

In [36]:
print(A)
print(A.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


### Reshape

In [37]:
print(np.reshape(A, (4, -1)))

[[1]
 [2]
 [3]
 [4]]


## Credits
Based on [Stanford CS228: Probabilistic Graphical Models material](https://github.com/kuleshov/cs228-material/blob/master/tutorials/python/cs228-python-tutorial.ipynb)